package com.example.numera.theme

import androidx.compose.ui.graphics.Color

// Shared colors
val CorrectGreen = Color(0xFF58CC02) // Duolingo green
val CorrectGreenPressed = Color(0xFF46A302)
val WrongRed = Color(0xFFEA2B2B)
val WrongRedPressed = Color(0xFFC21818)

// Duolingo Theme (Default Bright Theme)
val DuoBg = Color(0xFFFFFFFF)
val DuoPrimary = Color(0xFF58CC02) 
val DuoPrimaryPressed = Color(0xFF46A302)
val DuoSecondary = Color(0xFF1899D6) // Accent Blue
val DuoSecondaryPressed = Color(0xFF1482B5)
val DuoTertiary = Color(0xFFFF9600) // Accent Orange
val DuoTertiaryPressed = Color(0xFFE68500)
val DuoSurface = Color(0xFFFFFFFF)
val DuoSurfaceCard = Color(0xFFF7F7F7)
val DuoOnSurface = Color(0xFF3C3C3C)
val DuoBorder = Color(0xFFE5E5E5)
val DuoSubtext = Color(0xFF777777)

// Cyberpunk (Adapted to bright/rich flat 3D)
val CyberBg = Color(0xFFFAF0FF)
val CyberPrimary = Color(0xFFBD00FF)
val CyberPrimaryPressed = Color(0xFF9000C7)
val CyberSecondary = Color(0xFF00C2FF)
val CyberSecondaryPressed = Color(0xFF009BCB)
val CyberTertiary = Color(0xFFFF007F)
val CyberTertiaryPressed = Color(0xFFCC0066)
val CyberSurface = Color(0xFFFFFFFF)
val CyberSurfaceCard = Color(0xFFF6EAFF)
val CyberOnSurface = Color(0xFF3D1B4F)
val CyberBorder = Color(0xFFE3C4FF)

// Neon Eclipse (Adapted to bright/rich flat 3D)
val EclipseBg = Color(0xFFFFFDF5)
val EclipsePrimary = Color(0xFFD18A00)
val EclipsePrimaryPressed = Color(0xFF9E6800)
val EclipseSecondary = Color(0xFFC76200)
val EclipseSecondaryPressed = Color(0xFF9E4E00)
val EclipseTertiary = Color(0xFF219EBC)
val EclipseTertiaryPressed = Color(0xFF1A7F96)
val EclipseSurface = Color(0xFFFFFFFF)
val EclipseSurfaceCard = Color(0xFFFFF6DF)
val EclipseOnSurface = Color(0xFF473C21)
val EclipseBorder = Color(0xFFFCE19B)

// Emerald Abyss (Adapted to bright/rich flat 3D)
val EmeraldBg = Color(0xFFF4FDF8)
val EmeraldPrimary = Color(0xFF00CD76)
val EmeraldPrimaryPressed = Color(0xFF009C5A)
val EmeraldSecondary = Color(0xFF00A2C9)
val EmeraldSecondaryPressed = Color(0xFF0082A2)
val EmeraldTertiary = Color(0xFF7D3CFF)
val EmeraldTertiaryPressed = Color(0xFF632FD1)
val EmeraldSurface = Color(0xFFFFFFFF)
val EmeraldSurfaceCard = Color(0xFFE6FAF0)
val EmeraldOnSurface = Color(0xFF0A301E)
val EmeraldBorder = Color(0xFFBFF2DB)

// Crimson Nebula (Adapted to bright/rich flat 3D)
val CrimsonBg = Color(0xFFFFF5F6)
val CrimsonPrimary = Color(0xFFFA2C56)
val CrimsonPrimaryPressed = Color(0xFFCD1A3E)
val CrimsonSecondary = Color(0xFFFF725E)
val CrimsonSecondaryPressed = Color(0xFFDB5A47)
val CrimsonTertiary = Color(0xFFAC0037)
val CrimsonTertiaryPressed = Color(0xFF86002A)
val CrimsonSurface = Color(0xFFFFFFFF)
val CrimsonSurfaceCard = Color(0xFFFFE8EC)
val CrimsonOnSurface = Color(0xFF4B101C)
val CrimsonBorder = Color(0xFFFFAEC0)

// Aurora Borealis Theme
val AuroraBg = Color(0xFFF3FAF7)
val AuroraPrimary = Color(0xFF008A72)
val AuroraPrimaryPressed = Color(0xFF006C59)
val AuroraSecondary = Color(0xFF845EC2)
val AuroraSecondaryPressed = Color(0xFF6B4B9E)
val AuroraTertiary = Color(0xFFD65DB1)
val AuroraTertiaryPressed = Color(0xFFB14E93)
val AuroraSurface = Color(0xFFFFFFFF)
val AuroraSurfaceCard = Color(0xFFE5F5F0)
val AuroraOnSurface = Color(0xFF1B3B32)
val AuroraBorder = Color(0xFFBBE5D9)

// Deep Ocean Theme
val OceanBg = Color(0xFFF0F7FA)
val OceanPrimary = Color(0xFF0078AA)
val OceanPrimaryPressed = Color(0xFF005F86)
val OceanSecondary = Color(0xFF3AB4F2)
val OceanSecondaryPressed = Color(0xFF289ECE)
val OceanTertiary = Color(0xFF009664)
val OceanTertiaryPressed = Color(0xFF00754E)
val OceanSurface = Color(0xFFFFFFFF)
val OceanSurfaceCard = Color(0xFFE1EFF5)
val OceanOnSurface = Color(0xFF0A2B3C)
val OceanBorder = Color(0xFFB0DAEC)

// Sunset Horizon Theme
val SunsetBg = Color(0xFFFFF7F2)
val SunsetPrimary = Color(0xFFFF5F7E)
val SunsetPrimaryPressed = Color(0xFFE04966)
val SunsetSecondary = Color(0xFFFF9F29)
val SunsetSecondaryPressed = Color(0xFFE0861A)
val SunsetTertiary = Color(0xFFC66900)
val SunsetTertiaryPressed = Color(0xFF9E5400)
val SunsetSurface = Color(0xFFFFFFFF)
val SunsetSurfaceCard = Color(0xFFFFF0E5)
val SunsetOnSurface = Color(0xFF3A1C0E)
val SunsetBorder = Color(0xFFFDD5C0)

// Milestone Achievement (cross-theme — used for levels 10, 20, 30, 40, 50, 60)
val MilestoneGold      = Color(0xFFD4AF37)
val MilestoneGoldDark  = Color(0xFF9E7C00)
val MilestoneBg        = Color(0xFFFFFDF0)
val MilestoneSurface   = Color(0xFFFFF9DF)
val MilestoneBorder    = Color(0xFFE6CA65)
val MilestoneOnSurface = Color(0xFF4C3E08)

// Midnight Galaxy Theme
val MidnightBg = Color(0xFFF5F5FA)
val MidnightPrimary = Color(0xFF3F3B6C)
val MidnightPrimaryPressed = Color(0xFF302B52)
val MidnightSecondary = Color(0xFF624F82)
val MidnightSecondaryPressed = Color(0xFF4C3C67)
val MidnightTertiary = Color(0xFFA3C7D7)
val MidnightTertiaryPressed = Color(0xFF88A9B8)
val MidnightSurface = Color(0xFFFFFFFF)
val MidnightSurfaceCard = Color(0xFFEFEFF7)
val MidnightOnSurface = Color(0xFF1C1A27)
val MidnightBorder = Color(0xFFCECEDF)
